[package]
name = "faimg_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "faimg_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "0.18.3"
ndarray = "0.15"
numpy = "0.18"